''
'' A simple black on white theme (with blue hyperlinks)
''
'' Original Author: Matthew Leather
''

!$THEME = "plainblue"

!$BGCOLOR = "white"
!$BORDER = "#33668E"
' !$SECONDARY_LIGHT = "#0070C0"
!$SECONDARY_LIGHT = "#A3D1FF"
!$SECONDARY_DARK = navy
' !$SECONDARY_TEXT = "#FFFFFF"
!$SECONDARY_TEXT = $BGCOLOR

' !$INFO = "#ccf"
!$INFO = white
!$INFO_DARK = Navy
!$WHITE = "White"
!$FONT_COLOR_EMPHASIS = "#0F4A82"
!$BORDER_LINE = DarkGray
!$HEADING_BGCOLOR = "#082642"

!if %not(%variable_exists("$BGCOLOR"))
  !$BGCOLOR = "white"
!endif

!if %not(%variable_exists("$FGCOLOR"))
  !$FGCOLOR = "#000000"
!endif

!if %not(%variable_exists("$HYPERLINK_COLOR"))
  !$HYPERLINK_COLOR = "blue"
!endif

!ifndef $FONT_NAME
  !$FONT_NAME = "Helvetica"
!endif

!ifndef $FONT_NAME_MONOSPACED
  !$FONT_NAME_MONOSPACED = "Courier"
!endif

<style>
  root {
    BackgroundColor $BGCOLOR
    FontColor $FGCOLOR
    FontName $FONT_NAME
    HyperLinkColor $HYPERLINK_COLOR
    LineColor $FGCOLOR
    LineThickness 1
    Margin 5
  }
  caption {
    LineThickness 0
  }
  footer {
    LineThickness 0
  }
  header {
    LineThickness 0
  }
  node {
    MaximumWidth 300
  }
  title {
    FontSize 28
    LineThickness 0
  }

  activityDiagram {
  BackgroundColor #F0F0F0
  ' #E3E3E3
  BorderColor #33668E
  ' FontColor #000000
  FontName arial

  diamond {
    BackgroundColor #0070C0
    LineColor navy
    FontColor navy
    FontName arial
    FontSize 12
  }
  arrow {
    FontSize 12
  }
}
document {
   BackgroundColor transparent
}
</style>

skinparam defaultFontName "Helvetica"
skinparam defaultFontSize 16
skinparam dpi 100
skinparam ArrowLollipopColor $FGCOLOR
skinparam BackgroundColor $BGCOLOR
skinparam DefaultFontName $FONT_NAME
skinparam DefaultMonospacedFontName $FONT_NAME_MONOSPACED
skinparam LifelineStrategy nosolid
skinparam ParticipantPadding 10
skinparam SequenceLifeLineBorderColor $FGCOLOR
skinparam Shadowing false
skinparam UseBetaStyle true

!startsub activity
skinparam Activity {
  ' BackgroundColor $BGCOLOR
  ' BackgroundColor "#E3E3E3"
  BarColor $FGCOLOR
  BorderColor $FGCOLOR
  FontColor $FGCOLOR
  FontName $FONT_NAME

  DiamondBackgroundColor $SECONDARY_LIGHT
  DiamondBorderColor $SECONDARY_DARK
  DiamondFontColor $FGCOLOR
}
!endsub

!startsub node

skinparam node {
  BackgroundColor #E3E3E3
	BackgroundColor  $SECONDARY
	BorderColor $LIGHT
	FontColor $LIGHT
}
!endsub

skinparam Boundary {
  FontColor $FGCOLOR
}
skinparam Box {
  Padding 5
}
skinparam CircledCharacter {
  FontColor $FGCOLOR
  FontName $FONT_NAME_MONOSPACED
  Radius 9
}
skinparam Class {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam ClassAttribute {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam ClassStereotype {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam Footer {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam Header {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam Hyperlink {
  Color $HYPERLINK_COLOR
}
skinparam IconPackage {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam IconPrivate {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam IconProtected {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
skinparam IconPublic {
  Color $FGCOLOR
  BackgroundColor $BGCOLOR
}
' skinparam Note {
'   FontColor $FGCOLOR
'   FontName $FONT_NAME
' }
!startsub note
skinparam note {
	BorderThickness 1
	BackgroundColor $INFO
	BorderColor $INFO_DARK
	FontColor $FONT_COLOR_EMPHASIS
}
!endsub

!startsub swimlane
skinparam swimlane {
	BorderColor $BORDER_LINE
	BorderThickness 1
	TitleBackgroundColor $HEADING_BGCOLOR
	TitleFontColor $PRIMARY
}
!endsub

skinparam Object {
  BorderColor $FGCOLOR
}
skinparam Package {
  BorderColor $FGCOLOR
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
skinparam State {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}
skinparam StereotypeA {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}
skinparam StereotypeC {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}
skinparam StereotypeE {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}
skinparam StereotypeI {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}
skinparam StereotypeN {
  BackgroundColor $BGCOLOR
  BorderColor $FGCOLOR
}
skinparam UseCaseStereoType {
  FontColor $FGCOLOR
  FontName $FONT_NAME
}
